<?php

namespace App\Tests\Controller;

use App\DataFixtures\UserFixture;
use App\Entity\Address;
use App\Entity\User;
use Doctrine\Common\DataFixtures\Executor\ORMExecutor;
use Doctrine\Common\DataFixtures\Purger\ORMPurger;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\SchemaTool;
use Liip\TestFixturesBundle\Services\DatabaseToolCollection;
use Liip\TestFixturesBundle\Services\DatabaseTools\AbstractDatabaseTool;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class UserControllerTest extends WebTestCase
{
    protected EntityManagerInterface  $em;
    private ORMExecutor $executor;
    private ORMPurger $purger;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->em = self::getContainer()->get(EntityManagerInterface::class);
        $this->purger = new ORMPurger($this->em);
        $this->executor = new ORMExecutor($this->em, $this->purger);

        $this->executor->execute([new UserFixture()], true);
    }

    public function testGetUsers()
    {
        $users = ($this->em->getRepository(User::class))->findAll();
        //dd($users[0]);

        static::assertSame(1,1);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->executor->purge();
    }

}